config/routes.rb
Topzonenew::Application.routes.draw do
  devise_for :users

  resources :consultants
  resources :lessons
  resources :lessoncates
  
  namespace :admin do
     resources :lessons
  end

  namespace :admin do
     resources :lessoncates
  end
  
    namespace :admin do
     resources :consultants
  end

  
  root :to => 'index#index'
end

app/models/consultant.rb
class Consultant < ActiveRecord::Base
  has_many :lessons
  attr_accessible :address, :birthday, :company, :email, :histroy_lesson, :name, :phone, :photo_id, :position, :profession, :profile, :publish, :sex

  has_attached_file :excerpt_image, :styles => { :medium => "300*300>", :thumb => "100*100>"}
end

app/controllers/admin/consultants_controller.rb
class Admin::ConsultantsController < ApplicationController
  layout "admin"
  before_filter :require_is_admin
  # GET /consultants
  # GET /consultants.json
  def index
    @consultants = Consultant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @consultants }
    end
  end

  # GET /consultants/1
  # GET /consultants/1.json
  def show
    @consultant = Consultant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @consultant }
    end
  end

  # GET /consultants/new
  # GET /consultants/new.json
  def new
    @consultant = Consultant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @consultant }
    end
  end

  # GET /consultants/1/edit
  def edit
    @consultant = Consultant.find(params[:id])
  end

  # POST /consultants
  # POST /consultants.json
  def create
    @consultant = Consultant.new(params[:consultant])

    respond_to do |format|
      if @consultant.save
        format.html { redirect_to @consultant, notice: 'Consultant was successfully created.' }
        format.json { render json: @consultant, status: :created, location: @consultant }
      else
        format.html { render action: "new" }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /consultants/1
  # PUT /consultants/1.json
  def update
    @consultant = Consultant.find(params[:id])

    respond_to do |format|
      if @consultant.update_attributes(params[:consultant])
        format.html { redirect_to @aconsultant, notice: 'Consultant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultants/1
  # DELETE /consultants/1.json
  def destroy
    @consultant = Consultant.find(params[:id])
    @consultant.destroy

    respond_to do |format|
      format.html { redirect_to consultants_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/consultants_controller.rb
class ConsultantsController < ApplicationController
  
  # GET /consultants
  # GET /consultants.json
  def index
    @consultants = Consultant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @consultants }
    end
  end

  # GET /consultants/1
  # GET /consultants/1.json
  def show
    @consultant = Consultant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @consultant }
    end
  end

  # GET /consultants/new
  # GET /consultants/new.json
  def new
    @consultant = Consultant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @consultant }
    end
  end

  # GET /consultants/1/edit
  def edit
    @consultant = Consultant.find(params[:id])
  end

  # POST /consultants
  # POST /consultants.json
  def create
    @consultant = Consultant.new;(params[:consultant])

    respond_to do |format|
      if @consultant.save
        format.html { redirect_to @consultant, notice: 'Consultant was successfully created.' }
        format.json { render json: @consultant, status: :created, location: @consultant }
      else
        format.html { render action: "new" }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /consultants/1
  # PUT /consultants/1.json
  def update
    @consultant = Consultant.find(params[:id])

    respond_to do |format|
      if @consultant.update_attributes(params[:consultant])
        format.html { redirect_to @consultant, notice: 'Consultant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultants/1
  # DELETE /consultants/1.json
  def destroy
    @consultant = Consultant.find(params[:id])
    @consultant.destroy

    respond_to do |format|
      format.html { redirect_to consultants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/views/admin/consultants/_form.html.erb
<%= form_for(@consultant) do |f| %>
  <% if @consultant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consultant.errors.count, "error") %> prohibited this consultant from being saved:</h2>

      <ul>
      <% @consultant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
  	<%= f.label :upload_image %><br />
  	<%= f.file_field :excerpt_image%>
  	</div>

  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :profile %><br />
    <%= f.text_area :profile %>
  </div>
  <div class="field">
    <%= f.label :profession %><br />
    <%= f.text_area :profession %>
  </div>
  <div class="field">
    <%= f.label :histroy_lesson %><br />
    <%= f.text_area :histroy_lesson %>
  </div>
  <div class="field">
    <%= f.label :publish %><br />
    <%= f.text_area :publish %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/consultants/edit.html.erb
<h1>Editing consultant</h1>

<%= render 'form' %>


<%= link_to 'Show', @consultant %> |
<%= link_to 'Back', consultants_path %>

app/views/admin/consultants/index.html.erb
<h1>講師資料</h1>

<table class="data display datatable" id="example">
	<thead>
		<tr>
			<th>照片</th>
			<th>名字</th>
			<th>性別</th>
			<th>公司</th>
			<th>職位</th>
			<th>生日</th>
			<th>電話</th>
			<th>Email</th>
			<th>地址</th>
			<th>個人簡介</th>
			<th>專業</th>
			<th>教學經歷</th>
			<th>出版物</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @consultants.each do |consultant| %>
		<tr class="odd gradeX">
			<td><%= consultant.photo_id %></td>
			<td><%= consultant.name %></td>
			<td><%= consultant.sex %></td>
			<td><%= consultant.company %></td>
			<td><%= consultant.position %></td>
			<td><%= consultant.birthday %></td>
			<td><%= consultant.phone %></td>
			<td><%= consultant.email %></td>
			<td><%= consultant.address %></td>
			<td><%= consultant.profile %></td>
			<td><%= consultant.profession %></td>
			<td><%= consultant.histroy_lesson %></td>
			<td><%= consultant.publish %></td>
			<td><%= link_to '檢視', consultant %></td>
			<td><%= link_to '編輯', edit_admin_consultant_path(consultant) %></td>
			<td><%= link_to '刪除', consultant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<br />

<%= link_to '新增講師', new_consultant_path %>

app/views/admin/consultants/new.html.erb
<h1>New consultant</h1>

<%= render 'form' %>


<%= link_to 'Back', consultants_path %>

app/views/admin/consultants/show.html.erb
<p id="notice"><%= notice %></p>

<% if @consultant.excerpt_image %>
<p>
  <b>Photo:</b>
  <%= image_tag(@post.except_image.url(:medium)) %>
</p>
<% end %>

<p>
  <b>Name:</b>
  <%= @consultant.name %>
</p>

<p>
  <b>Sex:</b>
  <%= @consultant.sex %>
</p>

<p>
  <b>Company:</b>
  <%= @consultant.company %>
</p>

<p>
  <b>Position:</b>
  <%= @consultant.position %>
</p>

<p>
  <b>Birthday:</b>
  <%= @consultant.birthday %>
</p>

<p>
  <b>Phone:</b>
  <%= @consultant.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @consultant.email %>
</p>

<p>
  <b>Address:</b>
  <%= @consultant.address %>
</p>

<p>
  <b>Profile:</b>
  <%= @consultant.profile %>
</p>

<p>
  <b>Profession:</b>
  <%= @consultant.profession %>
</p>

<p>
  <b>Histroy lesson:</b>
  <%= @consultant.histroy_lesson %>
</p>

<p>
  <b>Publish:</b>
  <%= @consultant.publish %>
</p>


<%= link_to 'Edit', edit_consultant_path(@consultant) %> |
<%= link_to 'Back', consultants_path %>