config/routes.rb
Topzonenew::Application.routes.draw do
  devise_for :users

  resources :consultants
  resources :lessons
  resources :lessoncates
  
  namespace :admin do
     resources :lessons
  end

  namespace :admin do
     resources :lessoncates
  end
  
    namespace :admin do
     resources :consultants
  end

  
  root :to => 'index#index'
end

app/models/lessoncate.rb
class Lessoncate < ActiveRecord::Base
  has_many :lessons
  attr_accessible :name
end

app/controllers/admin/lessoncates_controller.rb
class Admin::LessoncatesController < ApplicationController
  layout 'admin'
  before_filter :require_is_admin

  # GET /lessoncates
  # GET /lessoncates.json
  def index
    @lessoncates = Lessoncate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lessoncates }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @lessoncate = Lessoncate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lessoncate }
    end
  end

  # GET /lessoncates/new
  # GET /lessoncates/new.json
  def new
    @lessoncate = Lessoncate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lessoncate }
    end
  end

  # GET /lessons/1/edit
  def edit
    @lessoncate = Lessoncate.find(params[:id])
  end

  # POST /lessoncates
  # POST /lessoncates.json
  def create
    @lessoncate = Lessoncate.new(params[:lessoncate])

    respond_to do |format|
      if @lessoncate.save
        format.html { redirect_to @lessoncate, notice: 'Lesson was successfully created.' }
        format.json { render json: @lessoncate, status: :created, location: @lessoncate }
      else
        format.html { render action: "new" }
        format.json { render json: @lessoncate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lessons/1
  # PUT /lessons/1.json
  def update
    @lessoncate = Lessoncate.find(params[:id])

    respond_to do |format|
      if @lessoncate.update_attributes(params[:lessoncate])
        format.html { redirect_to @lessoncate, notice: 'Lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lessoncate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lessoncate = Lessoncate.find(params[:id])
    @lessoncate.destroy

    respond_to do |format|
      format.html { redirect_to lessoncates_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/lessoncates_controller.rb
class LessoncatesController < ApplicationController
  # GET /lessoncates
  # GET /lessoncates.json
  def index
    @lessoncates = Lessoncate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lessoncates }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @lessoncate = Lessoncate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lessoncate }
    end
  end

  # GET /lessoncates/new
  # GET /lessoncates/new.json
  def new
    @lessoncate = Lessoncate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lessoncate }
    end
  end

  # GET /lessons/1/edit
  def edit
    @lessoncate = Lessoncate.find(params[:id])
  end

  # POST /lessoncates
  # POST /lessoncates.json
  def create
    @lessoncate = Lessoncate.new(params[:lessoncate])

    respond_to do |format|
      if @lessoncate.save
        format.html { redirect_to @lessoncate, notice: 'Lesson was successfully created.' }
        format.json { render json: @lessoncate, status: :created, location: @lessoncate }
      else
        format.html { render action: "new" }
        format.json { render json: @lessoncate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lessons/1
  # PUT /lessons/1.json
  def update
    @lessoncate = Lessoncate.find(params[:id])

    respond_to do |format|
      if @lessoncate.update_attributes(params[:lessoncate])
        format.html { redirect_to @lessoncate, notice: 'Lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lessoncate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lessoncate = Lessoncate.find(params[:id])
    @lessoncate.destroy

    respond_to do |format|
      format.html { redirect_to lessoncates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lessoncates_helper.rb
module LessoncatesHelper
end

app/views/admin/lessoncates/_form.html.erb
<%= form_for(@lessoncate) do |f| %>
  <% if @lessoncate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lessoncate.errors.count, "error") %> prohibited this lessoncate from being saved:</h2>

      <ul>
      <% @lessoncate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :課程分類名稱 %><br />
    <%= f.text_field :name%>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/lessoncates/edit.html.erb
<h1>Editing lesson</h1>

<%= render 'form' %>

<%= link_to '查看', @lessoncate %> |
<%= link_to '返回上一頁', lessoncates_path %>

app/views/admin/lessoncates/index.html.erb
<h2>分類瀏覽</h2>
<div class="block">

	<table class="data display datatable" id="example">
		<thead>
			<tr>
				<th>分類名稱</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @lessoncates.each do |lessoncate| %>
			<tr class="odd gradeX">
				<td align="center"><%= lessoncate.name %></td>

    <td><%= link_to '查看', lessoncate %></td>
    <td><%= link_to '編輯', edit_lessoncate_path(lessoncate) %></td>
    <td><%= link_to '刪除', lessoncate, method: :delete, data: { confirm: '你確定嗎?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '創建新分類', new_lessoncate_path %>

app/views/admin/lessoncates/new.html.erb
<h1>創建新分類</h1>

<%= render 'form' %>

<%= link_to '返回', lessoncates_path %>

app/views/admin/lessoncates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>分類名稱</b>
  <%= @lessoncate.name %>
</p>


<%= link_to 'Edit', edit_lesson_path(@lessoncate) %> |
<%= link_to 'Back', lessoncates_path %>