config/routes.rb
Topzonenew::Application.routes.draw do
  devise_for :users

  resources :consultants
  resources :lessons
  resources :lessoncates
  
  namespace :admin do
     resources :lessons
  end

  namespace :admin do
     resources :lessoncates
  end
  
    namespace :admin do
     resources :consultants
  end

  
  root :to => 'index#index'
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :lessoncate
  belongs_to :consultant
  attr_accessible :classtime, :content, :description, :lessoncate_id, :lessonhour, :place, :singtime, :string, :title ,:consultant_id
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < ApplicationController
  layout 'admin'
  before_filter :require_is_admin
  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lessons }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/new
  # GET /lessons/new.json
  def new
    @lesson = Lesson.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/1/edit
  def edit
    @lesson = Lesson.find(params[:id])
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(params[:lesson])

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render json: @lesson, status: :created, location: @lesson }
      else
        format.html { render action: "new" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lessons/1
  # PUT /lessons/1.json
  def update
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      if @lesson.update_attributes(params[:lesson])
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lessons }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/new
  # GET /lessons/new.json
  def new
    @lesson = Lesson.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/1/edit
  def edit
    @lesson = Lesson.find(params[:id])
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(params[:lesson])

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render json: @lesson, status: :created, location: @lesson }
      else
        format.html { render action: "new" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lessons/1
  # PUT /lessons/1.json
  def update
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      if @lesson.update_attributes(params[:lesson])
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :課程名稱 %><br />
    <%= f.text_field :title %>
  </div>
    <div class="field">
    <%= f.label :課程分類 %><br />
    <%= f.select :lessoncate_id, Lessoncate.all.map{ |c| [c.name, c.id] } %>
  </div>
     <div class="field">
    <%= f.label :講師 %><br />
    <%= f.select :consultant_id, Consultant.all.map{ |c| [c.name, c.id] } %>
  </div>
  <div class="field">
    <%= f.label :課程簡述 %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :課程內容 %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :報名時間 %><br />
    <%= f.date_select :singtime %>
  </div>
  <div class="field">
    <%= f.label :上課時間 %><br />
    <%= f.date_select :classtime %>
  </div>
  <div class="field">
    <%= f.label :上課地點 %><br />
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :課程時數 %><br />
    <%= f.text_field :lessonhour %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h2>Editing lesson</h2>
	<div class="block">

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

</div>

app/views/lessons/index.html.erb
<h2>課程瀏覽</h2>
<div class="block">

	<table class="data display datatable" id="example">
		<thead>
			<tr>
				<th>課程名稱</th>
				<th>課程分類</th>
				<th>課程敘述</th>
				<th>講師</th>
				<th>報名日期</th>
				<th>上課日期</th>
				<th>上課地點</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @lessons.each do |lesson| %>
			<tr class="odd gradeX">
				<td align="center"><%= lesson.title %></td>
				<td align="center"><%= lesson.lessoncate_id %></td>
				<td><%= lesson.description %></td>
				<td align="center"><%= lesson.consultant_id %></td>
				<td align="center"><%= lesson.singtime %></td>
				<td align="center"><%= lesson.classtime %></td>
				<td align="center"><%= lesson.place %></td>
				<td><%= link_to '查看', lesson %></td>
				<td><%= link_to '編輯', edit_lesson_path(lesson) %></td>
				<td><%= link_to '刪除', lesson, method: :delete, data: { confirm: '你確定嗎?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<br />

	<%= link_to '新增課程', new_lesson_path %>
</div>

app/views/lessons/new.html.erb
<h2>新增課程</h2>

<div class="block">
	<%= render 'form' %>

	<%= link_to '返回上一頁', lessons_path %>
</div>

app/views/lessons/show.html.erb
	<div class="block">
<p id="notice"><%= notice %></p>

<p>
  <b>課程分類:</b>
  <%= @lesson.lessoncate.name %>
</p>

<p>
  <b>課程:</b>
  <%= @lesson.title %>
</p>

<p>
  <b>課程簡介:</b>
  <%= @lesson.description %>
</p>

<p>
  <b>課程內容:</b>
  <%= @lesson.content %>
</p>

<p>
  <b>報名時間:</b>
  <%= @lesson.singtime %>
</p>

<p>
  <b>課程時間:</b>
  <%= @lesson.classtime %>
</p>

<p>
  <b>上課地點:</b>
  <%= @lesson.place %>
</p>

<p>
  <b>上課時數:</b>
  <%= @lesson.lessonhour %>
</p>




<%= link_to '編輯', edit_lesson_path(@lesson) %> |
<%= link_to '返回上一頁', lessons_path %>

</div>