config/routes.rb
Topzonenew::Application.routes.draw do
  devise_for :users

  resources :consultants
  resources :lessons
  resources :lessoncates
  
  namespace :admin do
     resources :lessons
  end

  namespace :admin do
     resources :lessoncates
  end
  
    namespace :admin do
     resources :consultants
  end

  
  root :to => 'index#index'
end

app/views/common/_admin_menu.html.erb
<div class="grid_12 header-repeat">
	<div id="branding">
		<div class="floatleft">
			<%= image_tag("logo.png")%>
		</div>
		<div class="floatright">
			<div class="floatleft">
				<%= image_tag("admin/img-profile.jpg")%>
			</div>
			<div class="floatleft marginleft10">
				<ul class="inline-ul floatleft">
					<li>
						<% if user_signed_in? %>
	                    HI <%= current_user.email%>
					</li>
					<li>
						<% if current_user && current_user.is_admin? %>
	                    <%= link_to("瀏覽前台", lessons_path, :target => '_blank')%>
	                    <%end%>
					</li>
					<li>
						<%= link_to("登出", destroy_user_session_path, :method => :delete)%>
						<% end %>
					</li>
				</ul>
				<br />
				<span class="small grey">Last Login: not support</span>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>
<div class="clear"></div>
<div class="grid_12">
	<ul class="nav main">
		<li class="ic-dashboard">
			<a href="/topadmin"><span>首頁</span></a>
		</li>
		<li class="ic-grid-tables">
			<a href="javascript:"><span>分析資料</span></a>
			
		</li>
		<li class="ic-form-style">
			<a href="typography.html"><span>課程系統</span></a>
		</li>
		<li class="ic-notifications">
			<a href="http://playplus.com.tw/"><span>聯絡Playplus</span></a>
		</li>
		
	</ul>
</div>

app/views/common/_admin_sidebar.html.erb
<div class="box sidemenu" style="height: 524px">
	<div class="block" id="section-menu">
		<ul class="section menu">
			<li>
				<a class="menuitem">課程管理</a>
				<ul class="submenu">
					<li>
						<a href="/admin/lessons/new">新增課程</a>
					</li>
					<li>
						<a href="/admin/lessons">瀏覽課程</a>
					</li>

				</ul>
			</li>
			<li>
				<a class="menuitem">課程分類管理</a>
				<ul class="submenu">
					<li>
						<a href="/admin/lessoncates/new">新增課程分類</a>
					</li>
					<li>
						<a href="/admin/lessoncates">瀏覽課程分類</a>
					</li>

				</ul>
			</li>
			<li>
				<a class="menuitem">講師管理</a>
				<ul class="submenu">
					<li>
						<a href="/admin/consultants/new">新增講師</a>
					</li>
					<li>
						<a href="/admin/consultants">瀏覽講師</a>
					</li>

				</ul>
			</li>

		</ul>
	</div>
</div>

app/views/common/_footer.html.erb
<div id="page_footer">
	<footer>
		<address>中華拓人服務管理顧問股份有限公司 CopyRight. All Right Reserved. Site powered by Play+Plus.
		</address>
	</footer>
</div>

app/views/common/_menu.html.erb
<div id="page_menubar">
		<div id="page_content_menu">
			<nav>
			<a href="http://www.playplus.com.tw/building/topzone/index.php"><%= image_tag("topzone_logo.png")%></a>
				<ul>
					<li><a href="http://playplus.com.tw/building/topzone/index.php">首頁</a></li>
					<li><a href="http://playplus.com.tw/building/topzone/about-us.php">關於中拓</a></li>
					<li><a href="#">服務項目</a>
						<ul>
							<li><a href="#">終身學習</a></li>
							<li><a href="#">企業訓練</a></li>
							<li><a href="#">顧問團隊</a></li>
							<li><a href="#">策略聯盟</a></li>
						</ul>
					</li>

					<li><a href="#">顧問團隊</a></li>
					<li><a href="http://playplus.com.tw/building/topzone/contact-us.php">聯絡我們</a></li>
					<li><a href="#">Like Us:<%= image_tag("follow-us-facebook.png")%></a></li>
				</ul>
			</nav>
		</div>
	</div>

app/views/common/_sidebar.html.erb
<div id="page_column">
	<div id="page_content_column" style="background-color: #e9e9e9; color:#000000">
		<div class="user_navigation">
			<% if user_signed_in? %>
			HI <%= current_user.email%>
			<%= link_to("登出", destroy_user_session_path, :method => :delete)%>
			<%else%>
			<%= link_to "登入", new_user_session_path %>
			<%= link_to "註冊", new_user_session_path %>
			<%end%>
		</div>
		<br/>
		2013-04-1
		<br/>
		asd
		<br/>
		News Feed
		<br/>
		<br/>
		News Feed
		<br/>
		<br/>
		News Feed
		<br/>
		<br/>
		News Feed
		<br/>
		<br/>
		News Feed
		<br/>
		<br/>
		News Feed
		<br/>
		<br/>
		News Feed
		<br/>
		<br/>
		News Feed
		<br/>
		<br/>
		News Feed
		<br/>
		<br/>
		News Feed
		<br/>
		<br/>
	</div>
</div>

app/views/common/_user_nav.erb
<div class="user_navigation">
	<% if user_signed_in? %>
	HI <%= current_user.email%>
	<%= link_to("登出", destroy_user_session_path, :method => :delete)%>
	 <% if current_user && current_user.is_admin? %>
	  <%= link_to("管理後台", admin_lessons_path )%>
	 <%end%>
	<%else%>
	<%= link_to "登入", new_user_session_path %>
	<%= link_to "註冊", new_user_session_path %>
	<%end%>
</div>